// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hryogdfnpsmahkisykqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyeW9nZGZucHNtYWhraXN5a3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1ODk2MDksImV4cCI6MjA1NzE2NTYwOX0.VorF5mPnWZevCadwpOVUTk5jKH5SAk8YfEWzvAKAI2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);